apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hueapi-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: basicapi
    spec:
      containers:
      - name: basicapi
        image: kidsan/hue-api
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: hueapi-service
spec:
  selector:
    app: hueapi
  ports:
    - protocol: TCP
      port: 80
  type: NodePort
